version: "3.4"
services:
  php:
    image: cdemo-php:32c94e9
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    # healthcheck:
    #   test: ps -ef | grep php-fpm | grep -v grep || exit 1
    #   interval: 5s
    #   timeout: 20s
  nginx:
    image: cdemo-nginx:32c94e9
    depends_on:
      - php
    ports:
      - "1212:80"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
